version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ems-consulta-aberta"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-sq8ix249mzov"
s3_prefix = "ems-consulta-aberta"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
